
from django.utils.translation import gettext as _

# Shortened list of contry names
COUNTRIES = (
    ('US', _('United States')),
    ('CA', _('Canada')),
    ('MX', _('Mexico')),
    ('GB', _('United Kingdom')),
    ('IN', _('India')),
    ('AR', _('Argentina')),
    ('AU', _('Australia')),
    ('AT', _('Austria')),
    ('BE', _('Belgium')),
    ('BZ', _('Belize')),
    ('BO', _('Bolivia')),
    ('BW', _('Botswana')),
    ('BR', _('Brazil')),
    ('BG', _('Bulgaria')),
    ('KH', _('Cambodia')),
    ('CM', _('Cameroon')),
    ('CL', _('Chile')),
    ('CN', _('China')),
    ('CO', _('Colombia')),
    ('CR', _('Costa Rica')),
    ('HR', _('Croatia')),
    ('CU', _('Cuba')),
    ('CZ', _('Czech Republic')),
    ('DK', _('Denmark')),
    ('DO', _('Dominican Republic')),
    ('EC', _('Ecuador')),
    ('EG', _('Egypt')),
    ('SV', _('El Salvador')),
    ('EE', _('Estonia')),
    ('ET', _('Ethiopia')),
    ('FI', _('Finland')),
    ('FR', _('France')),
    ('GE', _('Georgia')),
    ('DE', _('Germany')),
    ('GR', _('Greece')),
    ('GT', _('Guatemala')),
    ('HN', _('Honduras')),
    ('HK', _('Hong Kong')),
    ('HU', _('Hungary')),
    ('IS', _('Iceland')),
    ('ID', _('Indonesia')),
    ('IR', _('Iran')),
    ('IQ', _('Iraq')),
    ('IE', _('Ireland')),
    ('IL', _('Israel')),
    ('IT', _('Italy')),
    ('JP', _('Japan')),
    ('JO', _('Jordan')),
    ('KE', _('Kenya')),
    ('KR', _('South Korea')),
    ('KW', _('Kuwait')),
    ('LB', _('Lebanon')),
    ('LT', _('Lithuania')),
    ('MG', _('Madagascar')),
    ('MY', _('Malaysia')),
    ('MN', _('Mongolia')),
    ('NL', _('Netherlands')),
    ('NZ', _('New Zealand')),
    ('NG', _('Nigeria')),
    ('NO', _('Norway')),
    ('PK', _('Pakistan')),
    ('PS', _('Palestine')),
    ('PA', _('Panama')),
    ('PE', _('Peru')),
    ('PH', _('Philippines')),
    ('PL', _('Poland')),
    ('PT', _('Portugal')),
    ('PR', _('Puerto Rico')),
    ('QA', _('Qatar')),
    ('RO', _('Romania')),
    ('RU', _('Russian Federation')),
    ('SA', _('Saudi Arabia')),
    ('SG', _('Singapore')),
    ('ZA', _('South Africa')),
    ('ES', _('Spain')),
    ('LK', _('Sri Lanka')),
    ('SZ', _('Swaziland')),
    ('SE', _('Sweden')),
    ('CH', _('Switzerland')),
    ('TW', _('Taiwan')),
    ('TH', _('Thailand')),
    ('TR', _('Turkey')),
    ('UA', _('Ukraine')),
    ('AE', _('United Arab Emirates')),
    ('VE', _('Venezuela')),
    ('VN', _('Viet Nam')),
    ('ZW', _('Zimbabwe')),
    ('OO', _('Other')),
    )

